version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  report_data:
    run: r:latest analysis/report.R
    needs:
    - generate_study_population
    outputs:
      moderately_sensitive:
        csv: output/report_*.csv