version: '3.0'

expectations:
  population_size: 1000

actions:
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  report_data:
    run: r:latest analysis/report.R
    needs:
    - generate_study_population
    outputs:
      moderately_sensitive:
        csv: output/report_*.csv
        
  markdown_doc: 
    run:  r:latest -e 'rmarkdown::render("analysis/markdown_report.Rmd", output_dir = "output")'
    needs:  
    - generate_study_population
    outputs:  
      moderately_sensitive:  
        report: output/markdown_report.html

  generate_report:
    run: cohort-report:v3.0.0 output/input.csv
    needs: [generate_study_population]
    config:
      variable_types:
          CVD_assess_latest_date: date
          statins_prescribed: date
          age: int
          sex: categorical
          CVD_assess_latest_number: float
          CVD_assess_comparator: categorical
          CKD_code: binary
          CVD_code: binary
          T1D_code: binary
          T2D_code: binary
          Overall_diab_code: binary
      output_path: output/cohort_reports_outputs
    outputs:
      moderately_sensitive:
        reports: output/cohort_reports_outputs/descriptives_input.html
        reports_charts: output/cohort_reports_outputs/*.png
