version: '3.0'

expectations:
  population_size: 20000

actions:
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  markdown_doc: 
    run:  r:latest -e 'rmarkdown::render("analysis/markdown_report.Rmd", output_dir = "output")'
    needs:  
    - generate_study_population
    outputs:  
      moderately_sensitive:  
        report: output/markdown_report.html

  generate_report:
    run: cohort-report:v3.0.0 output/input.csv
    needs: [generate_study_population]
    config:
      variable_types:
          age: int
          sex: categorical
          CVD_assess_latest_number: float
          CVD_assess_latest_date: date
          CVD_assess_comparator: categorical
          cvdprevent_statins_issued_last_6m: date
          CKD_code: binary
          CVD_code_CVD_prevent: binary
          lipid_modifier_primary: date
          lipid_modifier_secondary: date
          T1D_code: binary
      output_path: output/cohort_reports_outputs
    outputs:
      moderately_sensitive:
        reports: output/cohort_reports_outputs/descriptives_input.html
        reports_charts: output/cohort_reports_outputs/*.png
